### ISSUE TITLE
Could you update the npm version of this package?

### ISSUE THREAD

**Issue by twang2218** [antelle/argon2-browser#10]
The version of 'argon2-browser' in NPM repository is outdated, `1.1.0`, which should be updated to `1.2.0`.

And I also tried to install via GitHub link directly: `npm install --save-dev antelle/argon2-browser#1.2.0`, and I found there is no `dist` or `docs` directory.

```bash
$ tree node_modules/argon2-browser
node_modules/argon2-browser
├── lib
│   └── argon2.js
├── package.json
└── README.md

1 directory, 3 files
```

Could you move the `dist` directory out of the `docs`, to the top level as well?

**Comment by antelle** [comment]
Published v1.3.0 with `dist`, thanks!
