### ISSUE TITLE
Can't reproduce build

### ISSUE THREAD

**Issue by Fang-** [antelle/argon2-browser#11]
I'm having trouble reproducing the build results as found in `/dist`.

The files I end up with are significantly shorter than the versions that ship with the repo, and moving them into `/docs/dist` gives me the following output in the browser console when clicking run on `test.html`:

```
wasm streaming compile failed: TypeError: NetworkError when attempting to fetch resource. argon2-asm.min.js:1:11123
falling back to ArrayBuffer instantiation argon2-asm.min.js:1:11169
on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS) argon2-asm.min.js:1:15088
on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS) argon2-asm.min.js:1:15098
failed to asynchronously prepare wasm: abort("on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)"). Build with -s ASSERTIONS=1 for more info. argon2-asm.min.js:1:10772
abort("on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)"). Build with -s ASSERTIONS=1 for more info. argon2-asm.min.js:1:15088
abort("on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)"). Build with -s ASSERTIONS=1 for more info. argon2-asm.min.js:1:15098
Module.intArrayFromString is not a function undefined test.html:22:19
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///Users/fang/softsrc/argon2-browser/docs/argon2-asm.min.wasm. (Reason: CORS request not http). 
```

I don't get any errors when running `build.sh`, as far as I can tell everything's completing fine. Could there be an emscripten configuration step that I missed? Or perhaps this has to do with me using the latest version of all the required tooling?

In case it's useful, I uploaded pastebins of my outputs for [`/dist/argon2.js`](https://pastebin.com/Jj92c22K) and [`/dist/argon2-asm.min.js`](https://pastebin.com/C27knW8S). You can see that especially the latter seems to be missing a lot of information compared to the version in the repo.

If you have any ideas here, they'd be much appreciated. Thank you for your time!

**Comment by antelle** [comment]
What’s your emsctipten and binaryen versions?
Could you please upload the build log somewhere?

**Comment by Fang-** [comment]
Emscripten 1.38.8. I think binaryen has the same version nr? Not sure how to find out. It's whatever came with the emscripten 1.38.8 install, which was latest as of yesterday.

Build log is [just this](https://pastebin.com/XKkDtxbj).

**Comment by antelle** [comment]
I'll close this, not sure what I can I do with it. Probably playing with different versions of compliers will eventually give a working result.
