### ISSUE TITLE
Support for Argon2id

### ISSUE THREAD

**Issue by poursal** [antelle/argon2-browser#14]
In the source I can see that there is support for d and i versions:

var ArgonType = {
        Argon2d: 0,
        Argon2i: 1
};

Am I missing something or there is not option to use the hybrid version Argon2id?

Thank you in advance for your great work.

**Comment by antelle** [comment]
Hi! You're right, it's not supported for now

**Comment by Slapbox** [comment]
@antelle are there plans to support it? It's the recommended version to use just about everywhere now. I'd really like to use your Argon2 implementation, but I need to support Argon2id. I'm far from being a cryptography expert, but is there anything I or others can do to help?

**Comment by antelle** [comment]
@Slapbox it's not supported in the library we use if I'm not mistaken. You can research it though, maybe it's already there and we can recompile it (I don't have time for this now).

**Comment by Slapbox** [comment]
Thanks for the speedy and honest response and for the hard work you put into this. It looks like @Fang- actually did a lot more in a commit just prior to that one.

**Comment by antelle** [comment]
@Slapbox yeah it looks like it's now supported there, nice.

**Comment by Fang-** [comment]
Also, #12 is still open, which merges in the latest reference implementation which does support Argon2id.

> How's this working for you? How did you test the output?

It's working great for us, though bundling was a bit of a nightmare. We tested against outputs from the reference implementation.  
For the most up-to-date version the fork that was linked, please see [urbit/argon2-wasm](https://github.com/urbit/argon2-wasm).

**Comment by Slapbox** [comment]
@Fang- That looks great! Thank you! Also, Urbit looks pretty great. I love the roadmap.

@antelle thanks again for your great work!

**Comment by antelle** [comment]
Updated it, now Argon2id is supported. 
@Fang- sorry I haven't used the proposed MR, it was just easier to copy&recompile.

**Comment by Fang-** [comment]
Ah, so now this works without any asm-js/wasm-specific C changes? Neat! I might have to try and pull those out of our fork too, then.

Thanks for finally supporting Argon2id here. (:

**Comment by antelle** [comment]
It seems to be working now yeah. At least it doesn't throw, as it was before.
