### ISSUE TITLE
Error: -33: Threading failure

### ISSUE THREAD

**Issue by Slapbox** [antelle/argon2-browser#15]
Entering a value of `2` for `parallelism` causes the following error: `Error: -33: Threading failure`

This affects every configuration and mode of running EXCEPT PNaCl. I'm seeing that on both mobile and desktop in Chrome.

@antelle @Fang- - Any ideas what might cause this? Is it possible to run Argon2 with parallelism in a browser environment? Particularly, is it possible on mobile?

**Comment by Slapbox** [comment]
Whoops, I see now in the docs this is mentioned as a limitation. Any way around it these days though?

**Comment by antelle** [comment]
oh wow, thanks, probably it tries to use new wasm threads api and fails. We should compile without pthreads to make it work like before.

**Comment by Slapbox** [comment]
Wow that was quick! Thank you so much for continuing to maintain this!

**Comment by Nantris** [comment]
@antelle are threads disabled again? Even if they're not advisable to use, why disable them? This makes verifying any hash with parallelism impossible.
