### ISSUE TITLE
Killing Firefox Quantum 65.0.2 (64-bit)

### ISSUE THREAD

**Issue by kangert** [antelle/argon2-browser#20]
It's probably some Firefox issue, so take it just like a warning.

Tested on three computers, live demo WebAssembly kills Firefox Quantum 65.0.2 (64-bit) Win 10 - hard crash, no error message, just goes down.

**Comment by antelle** [comment]
Hi! Is it with default settings? It doesn't crash for me.

**Comment by kangert** [comment]
Yes. I have installed fresh copy on one of the computers. It's quite weird since last Firefox is two weeks old. Some Win 10 update combination maybe. Trying some other WebAssembly demos, but everything works ok.

**Comment by antelle** [comment]
I guess, all you can do is submit the crash report to Mozilla.

**Comment by kangert** [comment]
So it's not Firefox (not alone). It's Avast. After uninstallation and reinstallation of the antivirus everything (and everywhere) works ok.

Thank you for your time

**Comment by antelle** [comment]
Interesting, I also have Avast, but it doesn't crash on macOS. Thanks for the investigation!
