### ISSUE TITLE
How to use wasm?

### ISSUE THREAD

**Issue by taoxinyi** [antelle/argon2-browser#21]
I change `loadScript(distPath + '/argon2-asm.min.js');` to `loadScript(distPath + '/argon2.min.js');`, then I can see `argon2.wasm` is successfully fetched in the browser, but it shows error `Cannot read property 'apply' of undefined` when using `argon.hash`.

Is there an easy way to use wasm?

**Comment by antelle** [comment]
Hi! There's an example here: https://github.com/antelle/argon2-browser/blob/master/docs/js/calc.js#L67
