### ISSUE TITLE
How to use with a bundler?

### ISSUE THREAD

**Issue by NikxDa** [antelle/argon2-browser#24]
Hey there,

thanks for providing this awesome module to the community! I am trying to get this package to work with Webpack & React, but it turns out to be quite the issue. I suspect it is because of the way that the `argon2.js`:

1. Uses a factory and does not have a default export (webpack will bundle it in a scope which afaik is unaccessible afterwards), and
2. Loads the asm-file from a `node_modules` folder which is supposed to be exposed (if I get this correctly)

I was able to get this to work with a bundler by copying both of these files, exposing the asm variant file, and then both adding a default export & changing the import path. Is there a way to get first hand support for bundlers so that this does not result in any issues? I suspect most people will not be willing to expose their node_modules, and I feel it is a really bad practice. On the other hand, my workaround will need to be updated manually, which might pose security risks at some point in time.

Would love to get your feedback on this!

Cheers

**Comment by antelle** [comment]
Hi!
Indeed exposing node_modules is not cool and it's supposed to be used mostly for debugging.  
Now WebPack has better support for loading WebAssembly, we can improve bundling as well. I'd be happy to see a merge request on this, but I'll also try to implement it.

**Comment by NikxDa** [comment]
Hey there,

thanks for checking on this so promptly! Happy to see what you can come up with. If you need any specific help, let me know!

Cheers

**Comment by NikxDa** [comment]
@antelle Did you get anywhere with this? I might have a look into it this weekend otherwise, but I'd appreciate your guidance in terms of how you imagine this should work out.

Cheers!

**Comment by antelle** [comment]
I haven’t done anything yet unfortunately, didn’t have time for that...

**Comment by Valgoku01** [comment]
Hi all,

I've had the same trouble. Working with argon2-browser on dev purpose doesn't cause any trouble cause you're working with node_modules. But as soon as you want it to be working on production (bundled), the problem occures indeed. It tries to import the lib from... node_modules...
I'd be very greatful of any improvement :)

ps: thanks for the already great work done !

**Comment by antelle** [comment]
Done. Links to examples in webpack and node.js: https://github.com/antelle/argon2-browser#usage

**Comment by antelle** [comment]
Also thanks to this dude for some tips: https://itnext.io/react-router-and-webpack-v4-code-splitting-using-splitchunksplugin-f0a48f110312 (can be helpful for you as well)

**Comment by NikxDa** [comment]
Thanks for getting this done, I really appreciate it!
