### ISSUE TITLE
Can not use JS Library as documented

### ISSUE THREAD

**Issue by ms140569** [antelle/argon2-browser#30]
Hi - if i try to use the Argon2 lib argon2-browser@1.8.0 (exactly as described in the documentation section "JS Library") with Firefox 68, i get:

ReferenceError: module is not defined
argon2.js:254:1
    <anonym> http://localhost:8000/node_modules/argon2-browser/lib/argon2.js:254

What have i done wrong?

**Comment by antelle** [comment]
Hi! Fixed that, also added an example of using the library in vanilla js: https://github.com/antelle/argon2-browser/tree/master/examples/vanilla

**Comment by rajhlinux** [comment]
I just downloaded the argon2-browser and when I use the "vanilla.js" example folder and then open the "index.html", I get something weird which says: "Output should appear here. If not, please check DevTools in your browser."

Here  is picture of it:
![Papa Johns Garlic Sauce Recipe](https://user-images.githubusercontent.com/61344181/115117484-cd06ee80-9f6c-11eb-8166-4b862a7c977b.jpg)

What's wrong with it?

**Comment by antelle** [comment]
The message suggests what to do next.

**Comment by antelle** [comment]
This issue is resolved. If you have something else, please open a new one, but with more details.
