### ISSUE TITLE
Cannot read property 'push' of undefined undefined

### ISSUE THREAD

**Issue by 382303784** [antelle/argon2-browser#31]
hi, I rebuilt this project, but it seems to be a problem.

//environment
ubuntu 16.04
nodejs 10.x.x

//Install emsdk
https://webassembly.org/getting-started/developers-guide/

//rebuild
./build.sh

//run
const argon2=require('./lib/argon2')
argon2.hash({ pass: 'password', salt: 'somesalt' })
    .then(h => console.log(h.hash, h.hashHex, h.encoded))
    .catch(e => console.error(e.message, e.code))

//result
Cannot read property 'push' of undefined undefined

**Comment by antelle** [comment]
Hi! Stack trace please.

**Comment by 382303784** [comment]
> Hi! Stack trace please.

OK.All here.

```
TypeError: Cannot read property 'push' of undefined
TypeError: Cannot read property 'push' of undefined

E:\work\czr-remix-ide\czr\czr_account.js\node_modules\argon2-browser\dist\argon2.js:63
            throw ex
            ^
abort(TypeError: Cannot read property 'push' of undefined). Build with -s ASSERTIONS=1 for more info.
```

//E:\work\czr-remix-ide\czr\czr_account.js\node_modules\argon2-browser\dist\argon2.js:63
```
process["on"]("uncaughtException", function (ex) {
        if (!(ex instanceof ExitStatus)) {
            throw ex
        }
    })

**Comment by antelle** [comment]
Whta's your emscripten version?

**Comment by 382303784** [comment]
I am installing emsdk:
```
./emsdk install latest
```
so,emscripten version is 1.38.42

**Comment by antelle** [comment]
I'm on `1.38.40`. If you see a line here: `argon2.js:63`, this means it's not compiled successfully. I can't reproduce it, not sure how I can help, looks like you need to fight it somehow.

**Comment by 382303784** [comment]
Originally one line, I formatted it for convenience.

The error before formatting is：
```argon2.js:1```

I am sorry, I forgot to tell you that I formatted the code.

**Comment by 382303784** [comment]
Hi! I think I found the problem, I used the ```1.38.40``` version to rebuild, and then it can be successful.

But I don't know why this error occurs with the ```1.38.42``` version.

Thank you very much for your help.

**Comment by antelle** [comment]
42 is not released yet ;)

**Comment by antelle** [comment]
No, that's actually latest now, so we should fix it.

**Comment by antelle** [comment]
Fixed, published 1.10.0 ☺️

**Comment by antelle** [comment]
Now we have [CI](https://travis-ci.org/antelle/argon2-browser), which builds on latest emscripten.

**Comment by 382303784** [comment]
that`s great!
