### ISSUE TITLE
Argon2d implementation equivalence

### ISSUE THREAD

**Issue by afrancht** [antelle/argon2-browser#34]
Hello, 

If I make use of argon2d-browser and hash a password in the client-side and then want to verify that hash in the server-side. Can I use a different Argon2d library to do so, like for example:  https://github.com/ranisalt/node-argon2, https://github.com/jdconley/argon2themax or https://github.com/cjlarose/argon2-ffi ??

Thank you

**Comment by antelle** [comment]
Hi! Yes, it's the recommended way of verifying it. Of course it's possible to use argon2-browser on server, but the WebAssembly implementation is less efficient.

**Comment by afrancht** [comment]
You are quick! I'm impressed!! Thanks!

**Comment by antelle** [comment]
The encoded version is hash + argon2 parameters, such as version used, parallelism, etc... If you want the library to read the parameters from it, you should store the encoded version; if you would like to provide them yourself, store the hash.
