### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by Alex-----** [antelle/argon2-browser#36]
Edge does not support the import() function used in lib/argon2.js. Also, https://antelle.net/argon2-browser/ does not work in Edge because TextEncoder is not defined.

**Comment by antelle** [comment]
Hi! I've fixed the demo in Edge.
Most likely you won't load the file like this in production, so import should be used only for making a demo / prototype. You can export `loadArgon2WasmModule` function to load the file properly in Edge.
For TextEncoder/Decoder, you will need a polyfill, which should be bundled separately indeed.
