### ISSUE TITLE
Argon2di support

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [antelle/argon2-browser#4]
Is the "new" argon2di mode supported, too?

**Comment by antelle** [comment]
What is it? I can’t find it on the format description page.

**Comment by tmolitor-stud-tu** [comment]
Sorry, had a typo. The name is Argon2id.
See here: https://en.wikipedia.org/wiki/Argon2
And here: https://www.cryptolux.org/images/0/0d/Argon2.pdf (page 5):
> Type y of Argon2: 0 for Argon2d, 1 for Argon2i, 2 for Argon2id.

**Comment by antelle** [comment]
No, only argon2d is supported, as described in [KDBX4 spec](http://keepass.info/help/kb/kdbx_4.html). If you have further comments regarding the format, it's for [KeePass forums](https://sourceforge.net/projects/keepass/support).

**Comment by Inkeliz** [comment]
I think will be nice to have the Argon2id support. The LibSodium chooses the Argon2id by default in the last version. :\

**Comment by Extarys** [comment]
I agree

**Comment by aerth** [comment]
Argon2id is missing: http://antelle.net/argon2-browser/
