### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by m-milosevic** [antelle/argon2-browser#41]
Hi,
Is there any possibility to use this library with Internet Explorer 11?

**Comment by antelle** [comment]
Hi!
Yes, if you don't mind some DIY.
The last version when we had asm.js support was 8856dd2b26a557fa8376579fe31c6eacc6c0c067, after this it was removed, so IE11 is no longer supported. You have two options:
1. stick to that version (1.5.3)
2. build the asm.js module on the latest version and fix what's required

**Comment by m-milosevic** [comment]
Than you for your replay.
