### ISSUE TITLE
Optional secret data support for hashing the password.

### ISSUE THREAD

**Issue by DomainFlag** [antelle/argon2-browser#44]
Does it have support for providing the optional secret data besides the password / salt for keyed hashing? If not, can you provide any tips how to achieve that? Thanks.

**Comment by antelle** [comment]
Hi! If I'm not mistaken, you can make keyed hashing from any cryptographic hash function. However Argon2 is a not a hashing function per se and it's designed to me computation-hard, it's not clear why you need it for keyed hashing.
I'd suggest asking in the [argon2 repo](https://github.com/P-H-C/phc-winner-argon2) itself though, it's just a fork for WebAssembly, probably you'll get better advice there.

**Comment by DomainFlag** [comment]
@antelle thanks for the quick response, I mean that I am using the [Argon2 Repo](https://github.com/P-H-C/phc-winner-argon2)  the official one in Objective-C + Swift and if you have a look at the argon2_context that they use to initialize before key derivation, there is an optional secret data parameter used for keyed hashing that allows a secret key to be an extra input at hashing time. But, the argon2.hash in your repo does not support such parameter if I am not mistaken?

**Comment by antelle** [comment]
I see, didn't know it supported this parameter, thanks for pointing that out! It makes sense to add support indeed.

**Comment by antelle** [comment]
Done, now you can do this:
```js
argon2.hash({
    secret: new Uint8Array([...]), // optional secret data
    ad: new Uint8Array([...]), // optional associated data
})
```
