### ISSUE TITLE
ReferenceError: process is not defined (WebPack build issue)

### ISSUE THREAD

**Issue by tbelch-at-eHealth-Tec** [antelle/argon2-browser#46]
Hi it's me again!

I can't seem to get it running with webpack and create-react-app. Maybe you @antelle could have a look? Do you have an idea? 

It does build, but when I open the project in the browser (being served by the webpack dev server), it doesn't load the application but throws this error:

```
Uncaught ReferenceError: process is not defined
    at Object../node_modules/chalk/index.js (index.js:8)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object../node_modules/react-dev-utils/formatWebpackMessages.js (formatWebpackMessages.js:10)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object../node_modules/react-dev-utils/webpackHotDevClient.js (webpackHotDevClient.js:22)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object.1 (serviceWorker.js:141)
``` 

Here is my minimal project: https://github.com/tbelch-at-eHealth-Tec/argon2-browser/tree/cra_a2b-webpack

I appreaciate any help!

Best regards,
Tobias

**Comment by antelle** [comment]
Where does it throw this error? I see that `process` is wrapped in `global` in argon2 library code.

**Comment by tbelch-at-eHealth-Tec** [comment]
The error is thrown here:

![image](https://user-images.githubusercontent.com/64063903/87165989-31549d80-c2cb-11ea-80cc-c51d2ab2c501.png)

I also tried building the project and simply serving it. Then I'll get the following error message:

![image](https://user-images.githubusercontent.com/64063903/87164945-b939a800-c2c9-11ea-922f-271fb65c3de2.png)

argon2.wasm:1 resolves to

![image](https://user-images.githubusercontent.com/64063903/87165019-d4a4b300-c2c9-11ea-9c5e-a886d416e017.png)

Where is `process` wrapped in `argon2`?

**Comment by antelle** [comment]
I see that it's not our code, there's some other module that reads from `process`. In argon2 it's here:
https://github.com/antelle/argon2-browser/blob/master/lib/argon2.js#L30
