### ISSUE TITLE
Update readme to clarify that asm.js is no longer used

### ISSUE THREAD

**Issue by nivekuil** [antelle/argon2-browser#49]
Hi, thanks for writing this library. I noticed that the readme still insists that asm.js is being used in the browser, but I understand it's been removed since 1.5.3, so the readme should probably be updated to reflect that.

**Comment by antelle** [comment]
Thanks for the reminder! The readme seems to be very old, I'll update it.

**Comment by fellowseb** [comment]
On this subject, @antelle how would you recommend using this library while adding a fallback to asm.js for browsers not supporting WASM ? Thanks !

**Comment by antelle** [comment]
Those browsers are either old and unsupported, or built with a specific purpose. I would recommend not using cryptography in outdated and unmaintained browsers. It you still would like to do it, you can load one if old versions of the package from npm.
