### ISSUE TITLE
How to use WASM version?

### ISSUE THREAD

**Issue by TomMettam** [antelle/argon2-browser#51]
Hello!

I'm trying to use the WASM version of argon2-browser in an Angular project.

I've configured the Webpack loader as per https://github.com/antelle/argon2-browser/tree/master/examples/webpack

Everything seems to go fine, except the performance i'm seeing is more in line with the asm.js version and not the WASM version (I'm comparing with the benchmark here: https://caspertech.github.io/crypto-hash-benchmarks.github.io/

Is there anything special I need to do to get it to use the wasm version?

**Comment by antelle** [comment]
Hi! There’s no asm.js version anymore, the only one is wasm.
