### ISSUE TITLE
Memory limit

### ISSUE THREAD

**Issue by hcksw** [antelle/argon2-browser#55]
I’ve noticed that the maximum memory has been reduced to 256MB. Above this results in a error (memory allocation error -22). 
Previously I could run this up to 1GB. I’m guessing something has been changed in a recent code update. 
Is it possible to return to a higher memory potential? Argon2 is frequently used at 512MB or higher as it results in a 1 second calculation time on a native implementation.

**Comment by antelle** [comment]
Hi! I just tested it, memory up to ≈2GB it works for me in Chrome, Safari, and Firefox. Also added a test for it and I see that it's passing on CI: https://github.com/antelle/argon2-browser/runs/1545181588
How do you see that memory is limited to 256MB?

**Comment by hcksw** [comment]
Hi. You are correct. It’s working fine on Safari and Firefox. I was trying it on the DuckDuckGo browser on iOS, which worked fine before but not in the past few days. There was a recent update to that browser so I suspect that is causing the problem.

**Comment by antelle** [comment]
Does it work on https://antelle.net/argon2-browser/ in that browser?

**Comment by antelle** [comment]
Just tried it, it works in this browser: [screenshot](https://user-images.githubusercontent.com/633557/102017050-bfdeb680-3d64-11eb-9646-d0cb0e0232d1.PNG).
