### ISSUE TITLE
What settings do you recommend please?

### ISSUE THREAD

**Issue by lakano** [antelle/argon2-browser#6]
Thank you for this useful library porting to JS!

Do you recommend some iteration/memory settings to support the majority of devices please?
For example, there is many people that uses mobile with small capabilities (512MB RAM / 1Ghz CPU for an iPhone 4S).

EDIT: I think the best option is to make some settings tests when the user sign up, and to keep the settings used for this user's device, to be uses when the user sign in. [I've explained this here](https://crypto.stackexchange.com/a/53009/51301).

**Comment by antelle** [comment]
Hi,
It depends on your goals, there's no general guide here. You can try some settings and check if time/complexity ratio is enough for you.
Also, on iPhone 4S there's no WebAssembly and it will be much slower, but I don't have an estimate, you need to test it on a real device.
