### ISSUE TITLE
Javascript in Vanilla mode does not work out from the box.

### ISSUE THREAD

**Issue by rajhlinux** [antelle/argon2-browser#60]
![Papa Johns Garlic Sauce Recipe](https://user-images.githubusercontent.com/61344181/115117721-05f39300-9f6e-11eb-85ca-34fae81c787b.jpg)

What I am suppose to do to make Argon2-browser to work?

**Comment by antelle** [comment]
Hi! Network can reveal why argon2.js is not found.

**Comment by rajhlinux** [comment]
![Papa Johns Garlic Sauce Recipe](https://user-images.githubusercontent.com/61344181/115118313-99c65e80-9f70-11eb-8849-9bafb34e06ba.jpg)

Shows that "argon.js" file not found.

There are three versions of "argon.js" in the master file, which one to use and place it in the index source?

**Comment by antelle** [comment]
It won't work on `file://` schema, host it somewhere.

**Comment by rajhlinux** [comment]
Alright, will let you know if it works.

**Comment by rajhlinux** [comment]
![Papa Johns Garlic Sauce Recipe](https://user-images.githubusercontent.com/61344181/115119187-178c6900-9f75-11eb-822f-6266a20b1130.jpg)

Alright I installed "XAMPP". I only placed the vinalla JS example folder to be hosted.
Still having the same issue but this time without the `file://` error.

I checked the index.html file in the example folder and it's trying to find:
`node_modules/argon2-browser/lib/argon2.js
`
There is no such directory structure in the master folder. 
But there is 3 of `argon.js` in the master folder in different directories, which particular one should I use?

**Comment by antelle** [comment]
have you run `npm i` in the example folder?

**Comment by rajhlinux** [comment]
No, I do not use node.js

My backend will be using pure C++ web server framework called "Dragon" it is open source and fastest in the world.
Backend will not be anything other than C++.
I am trying to have the client side to do the hashing rather than the back end side.

**Comment by antelle** [comment]
Well, you need to install node_modules in the example, as if you would do in your webapp:

![image](https://user-images.githubusercontent.com/633557/115119446-a9619980-9fa8-11eb-86d5-0a2d1c2ed2f1.png)
