### ISSUE TITLE
Bundled version / just one js file in released version?

### ISSUE THREAD

**Issue by JsBergbau** [antelle/argon2-browser#61]
Is it possible to provide a bundled version in the releases? So you have one js file which you can include via `<script src>` and you can start. This would save really a lot of time and issues like https://github.com/antelle/argon2-browser/issues/60

**Comment by antelle** [comment]
It is possible, but needs some work.

**Comment by JsBergbau** [comment]
From my point of view this work would save a lot of people's work and time so it would be a great investment.

**Comment by JsBergbau** [comment]
For users that just want a fast argon2 javascript implementation it would also help a lot to add that to README.md like:

Note: argon2.js is not the whole library which needs to integrated. If you want a quick start it is recommended to use all requirements bundled into one js file. 
Therefore please go to `examples\webpack` and exec 
npm i 
npx webpack
After that you have file `bundle.js` in dist-folder. You can use this file via `<script src=>` to use argon2 in your Webpage. 

Or put this text in \examples\webpack folder. Same with `npm i` for "vanilla" folder. I mean for you as JavaScript developer this is basics. For me who just wants a fast solution for a little projects I need quite a lot of time to learn these things compared to just use a prebuild all in one file. 
With bundled file pre-build you save a lot of people time installing npm, reading all the instructions for just building a bundled argon2 Javascript library. 
I would call this bundled js file something like argon2LibReadyToUse or something similar, just to make clear that this file needs just to be included via `<script src>`.

For those who find this issue, I've attached version 1.15.4 as bundled-js file
[argon2Library.zip](https://github.com/antelle/argon2-browser/files/6542379/argon2Library.zip)

**Comment by JsBergbau** [comment]
For me it is also very confusing to download a release image and then to get it work having to download the actual code via npm. So a argon2 library in one js file would be really great.

**Comment by antelle** [comment]
I've added a bundled version in d71f437298c305501ce254fed7d09b3122601aa8, but it needs some more work because bintray is not anymore so publishing is now broken.

**Comment by antelle** [comment]
Done! v1.16.0 provides `dist/argon2-bundled.min.js`, here you can see it in action: https://jsfiddle.net/vqzrtupw/

**Comment by JsBergbau** [comment]
Thank you very much this helps a lot.
