### ISSUE TITLE
How to verify an Argon2 Hash?

### ISSUE THREAD

**Issue by ibudisteanu** [antelle/argon2-browser#7]
How do you verify an Argon2 Hash with this library in the browser?

**Comment by antelle** [comment]
Hi! There's no way to do it with the current setup.
If you need verification function, you can add it here: https://github.com/antelle/argon2-browser/blob/master/build-wasm.sh#L8, to `EXPORTED_FUNCTIONS` list. However I haven't tested it, maybe some fixes will be required.

**Comment by Slapbox** [comment]
@antelle - Is there any chance of seeing plain old JavaScript support for hash verification? Seems like the last missing piece to a perfect, browser-friendly Argon2 implementation.

**Comment by Slapbox** [comment]
If all my Github issues were resolved as quickly as the ones in this repo I'd be a year ahead of schedule!

Thank you @antelle!
