### ISSUE TITLE
cmake build warning on linux

### ISSUE THREAD

**Issue by pbertin-oneex** [antelle/argon2-browser#74]
Hello @antelle,

building on linux (20.04) with cmake v3.16.3 and emcc v2.0.32, I have this warning:

```
emcc: warning: EXTRA_EXPORTED_RUNTIME_METHODS is deprecated, please use EXPORTED_RUNTIME_METHODS instead [-Wdeprecated]
```

I'll make a PR with the little change if you are ok with that. 👍

**Comment by antelle** [comment]
Hi! Indeed you can change it, or I'll do it when it becomes an error.

**Comment by pbertin-oneex** [comment]
Thanks @antelle !
