### ISSUE TITLE
Import is an empty module in Vite

### ISSUE THREAD

**Issue by billy4479** [antelle/argon2-browser#75]
```ts
import * as argon2 from 'argon2-browser'
console.log(argon2.hash) // undefined
```

I'm using Vite as bundler and Typescript

**Comment by antelle** [comment]
Sounds like bundler issues

**Comment by ooesili** [comment]
@billy4479 did you ever figure this out?

**Comment by billy4479** [comment]
Not really, I ended up the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) but there are many forks that work fine with Vite, just have a look on npm, they are not as popular as this package but they are there.
#78 would probably fix this but it sill hasn't been merged at the time writing. I think the author has published an npm package with the changes though.

**Comment by davidyuk** [comment]
> I think the author has published an npm package with the changes though.

it is published as @aeternity/argon2-browser

**Comment by luojinzhang** [comment]
I added this to `vite.config.ts` to make it work with vite
```
resolve: {
    alias: {
      'argon2-browser': path.resolve(
       'path/to/root',
        'node_modules/argon2-browser/dist/argon2-bundled.min.js'
      ),
    },
  }
