### ISSUE TITLE
Chrome browser is refusing to execute the script.

### ISSUE THREAD

**Issue by volkovasystems** [antelle/argon2-browser#9]
I'm encountering this error log because attribute "type" in the code is not populated with correct MIME type.

Refused to execute script from 'http://localhost:3000/public/lib/argon2-browser/docs/dist/argon2-asm.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by antelle** [comment]
Hi,
You need to tune your CSP to fix this.
